twiclo/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'twiclo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'twiclo.views.home', name='home'),   # TODO: Que si estoy logueado muestre mis twicles y los de quienes sigo
    url(r'^admin/', include(admin.site.urls)),

    url(r'^u/', include('userprofile.urls', namespace='userprofile')),
    url(r'^t/', include('twicler.urls', namespace='twicler')),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # TODO: Hacer login


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twiclone/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^$', 'twicles.views.home', name='home'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^register/$', 'users.views.register', name='register'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^u/', include('users.urls', namespace='users')),
    url(r'^t/', include('twicles.urls', namespace='twicles')),

    url(r'^api/', include('siteapi.urls', namespace='api')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# coding=utf-8
__author__ = 'gabriel'

from twiclone.settings import username_regex
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^post_new_tag_form/$',
        views.post_new_tag_form,
        name='post_new_tag_form'),

    url(r'^post_profile_form/$',
        views.post_profile_form,
        name='post_profile_form'),

    url(r'^post_edit_tags_form/$',
        views.post_edit_tags_form,
        name='post_edit_tags_form'),

    url(r'^follow_control/$',
        views.follow_control,
        name='follow'),

    url(r'^(?P<username>' + username_regex + r')/$',
        views.show_profile,
        name='show_profile'),
)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <script src="{% static "js/jquery-2.1.1.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/jquery.cookie.js" %}"></script>

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block extra_headers %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <ul class="nav navbar-nav"><li class="active"><a href="{% url 'home' %}">Inicio</a></li></ul>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% load rehumanize %}
                    <li><a href="">Link</a></li>
                </ul>

                <ul class="nav navbar-nav">
                    <li class="divider-vertical"></li>
                    <li><a href="">Link</a></li>

                    {% if not request.user.is_anonymous %}
                    <li><a href="">Link no anónimo</a></li>
                    {% endif %}

                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="active2">

                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'register' %}">Registrarse</a></li>
                            <li><a href="{% url 'login' %}">Login</a></li>
                        {% else %}
                            <p class="navbar-text navbar-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<b class="caret"></b></a>
                                    <ul class="dropdown-menu">

                                        {% if user.is_staff %}
                                            <li><a href="{% url 'admin:index' %}">Panel de administración</a></li>
                                            <li class="divider"></li>
                                        {% endif %}

                                        <li><a href="">Logout</a></li>
                                    </ul>
                                </li>
                            </p>
                        {% endif %}

                    </li>
                </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block content %}

                {%  endblock content %}
            </div>
        </div>

    </div> <!-- container -->

    {% block bottom_scripts %}
    {% endblock bottom_scripts %}

</body>
</html>

templates/base_profile_with_timeline.html
{% extends 'base.html' %}
{% load humanize rehumanize static crispy_forms_tags %}


{% block extra_headers %}
    <link href="{% static "edit_profile.css" %}" rel="stylesheet">
{% endblock extra_headers %}


{% block content %}

    {#  Profile  #}
    {% if profile_form.errors %}
        <ol>
            {{ profile_form.errors }}
        </ol>
    {% endif %}

    {% if edition_allowed %}
    <form id="edit_profile_form" enctype="multipart/form-data" method="post" action="{% url 'users:post_profile_form' %}">
        {{ profile_form.user_id }}
        {{ profile_form.next }}
        {% csrf_token %}
    {% endif %}

    <div class="row"> <!-- Profile summary -->
        <div class="col-md-4">

            <!-- Avatar -->

            <span class="info_element">
                <img src="{{ profile.avatar.url }}" alt="{{ profile.username }}" class="img-thumbnail">
            </span>

            {% if edition_allowed %}
            <span class="edit_profile_form_element">
                {{ profile_form.avatar }}
            </span>
            {% endif %}

            <!-- Edit controls -->

            {% if edition_allowed %}
            <button id="edit_profile_button" type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-edit"></span>
            </button>
            {% else %}
                {# This user is not me, therefore I may [un]follow it #}

                {% if user.is_authenticated %}
                    {% if user != profile %}
                        <script>
                        {#  Set variable so the script knows where to post  #}
                        var follow_control_url="{% url 'users:follow' %}";
                        var follow_control_username="{{ profile.username }}";

                        {% if display_unfollow %}
                            var follow_control_action="u";
                        {% else %}
                            var follow_control_action="f";
                        {% endif %}

                        </script>
                        <script src="{% static "follow_control.js" %}"></script>



                        <a id="follow_control_button" href="#">
                            {% if display_unfollow %}
                                Dejar de seguir
                            {% else %}
                                Seguir
                            {% endif %}
                        </a>
                    {% endif %}
                {% endif %}
            {% endif %}

            <span class="edit_profile_form_element">
                <button type="submit" name="profile_form" class="btn btn-default"/>
                <span class="glyphicon glyphicon-ok"></span>
                </button>
            </span>

        </div>

        <!-- User name and Bio -->

        <div class="col-md-8">
            <h1>{{ profile.username }}</h1>
            <div class="well well-sm">

                <span class="info_element">{{ profile.bio }}</span>

                {% if edition_allowed %}
                <span class="edit_profile_form_element">{{ profile_form.bio }}</span>
                {% endif %}

            </div>
        </div>
    </div>

    {% if edition_allowed %}
    </form>
    {% endif %}

    <!-- Follow info -->

    <div class="row">
        <div class="col-md-2 col-md-offset-5">
            folowers: {{ followers_count }}
        </div>
        <div class="col-md-2 col-md-offset-2">
            following: {{ following_count }}
        </div>
    </div>

    <!-- Interest tags -->

    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                        Interest tags
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Tags</h3>

                            {% if edition_allowed %}

                                <!-- Select tags -->
                                {% crispy edit_tags_form %}

                                <!-- Add tag -->
                                {% include 'twicles/new_tag_form.html' %}

                            {% else %}
                                <ul>
                                    {% for tag in interest_tags %}
                                        <li>{{ tag.tag_name }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    {% block twicle_list_top %}
    {% endblock twicle_list_top %}


<div class="row">

    {#  Twicle list container  #}
    <div class="col-md-12">
        <ul class="list-group">
        <li class="list-group-item">{{ TODO }}</li>
        {% for twicle in twicles %}
            <li class="list-group-item">
                    <div class="row">   {# Twicle content #}

                        <div class="col-xs-2">  {# User avatar #}
                            <a href="{% url 'users:show_profile' twicle.author.username %}">
                                <img src="{{ twicle.author.avatar.url }}" class="img-thumbnail" />
                            </a>
                        </div>

                        <div class="col-md-10">  {# Twicle content #}

                            <div class="row">   {# Username #}
                                <div class="col-md-12">
                                    <a href="{% url 'users:show_profile' twicle.author.username %}">
                                        @{{ twicle.author.username }}
                                    </a>
                                </div>
                            </div>

                            <div class="row">   {# Content #}
                                <div class="col-md-12">
                                    {{ twicle.text }}
                                </div>
                            </div>

                        </div>

                    </div>

                    {% if twicle.image %}
                    <div class="row">   {# Twicle image, if present #}
                        <div class="col-md-12">
                            <a href="{{ twicle.image.url }}" class="thumbnail">
                                <img src="{{ twicle.image.url }}" class="img-thumbnail" />
                            </a>
                        </div>
                    </div>
                    {% endif %}

                    <div class="row">   {# Twicle meta #}
                        <div class="col-md-12">
                            {{ twicle.created | naturaltime | rehumanize }}
                        </div>
                    </div>

            </li>
        {% endfor %}
        </ul>
    </div>
</div>

{% endblock content %}

{% block bottom_scripts %}
    <script src="{% static "edit_profile_control.js" %}"></script>
{% endblock bottom_scripts %}