twicler/urls.py
# coding=utf-8
__author__ = 'gabriel'

from django.conf.urls import patterns, url
from twicler import views

urlpatterns = patterns('',
    url(r'^(?P<username>.+)/follow/$', views.follow, name='follow'),
    url(r'^(?P<username>.+)/$', views.view_twicles, name='view'),

)

twiclo/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'twiclo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'twiclo.views.home', name='home'),   # TODO: Que si estoy logueado muestre mis twicles y los de quienes sigo
    url(r'^admin/', include(admin.site.urls)),

    url(r'^u/', include('userprofile.urls', namespace='userprofile')),
    url(r'^t/', include('twicler.urls', namespace='twicler')),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # TODO: Hacer login


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twiclone/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^$', 'twicles.views.home', name='home'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^register/$', 'users.views.register', name='register'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^u/', include('users.urls', namespace='users')),
    url(r'^t/', include('twicles.urls', namespace='twicles')),

    url(r'^api/', include('siteapi.urls', namespace='api')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# coding=utf-8
__author__ = 'gabriel'

from twiclone.settings import username_regex
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^post_new_tag_form/$',
        views.post_new_tag_form,
        name='post_new_tag_form'),

    url(r'^post_profile_form/$',
        views.post_profile_form,
        name='post_profile_form'),

    url(r'^post_edit_tags_form/$',
        views.post_edit_tags_form,
        name='post_edit_tags_form'),

    url(r'^follow_control/$',
        views.follow_control,
        name='follow'),

    url(r'^(?P<username>' + username_regex + r')/$',
        views.show_profile,
        name='show_profile'),
)

twicler/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import User


class Twiclo(models.Model):
    # TODO: Describir qué es cada modelo
    text = models.CharField(max_length=200)
    author = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="twiclo_images", null=True)

    def __str__(self):
        return self.text


class UserSettings(models.Model):
    PUBLIC = 'PU'       # Everyone can see
    FOLLOWING = 'FI'    # Only those i'm following can see

    VISIBILITY_CHOICES = (
        (PUBLIC, 'Public'),
        (FOLLOWING, 'Those I follow'),
    )

    user = models.OneToOneField(User)
    visibility = models.CharField(max_length=2,
                                  choices=VISIBILITY_CHOICES,
                                  default=PUBLIC)

    following = models.ManyToManyField('self')
    followers = models.ManyToManyField('self')

    twicles_per_page = models.PositiveSmallIntegerField(default=10)

twicler/forms.py
# coding=utf-8
__author__ = 'gabriel'

from django import forms
from twicler.models import Twiclo


class NewTwicleForm(forms.ModelForm):

    image = forms.ImageField(required=False)

    class Meta:
        model = Twiclo
        fields = ['text', 'image']

twicler/views.py
# coding=utf-8
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from twicler.models import Twiclo
from twicler.forms import NewTwicleForm


def view_twicles(request, username):    # TODO: Manejar el post del twicle en otra view
    """
    Shows the last twicles of the given user
    If this is the request.user page, allows for publication of new twicles
    """
    user_shown = get_object_or_404(User, username=username)

    if request.method == 'POST' and request.user == user_shown:
        form_new_twicle = NewTwicleForm(request.POST, request.FILES)
        if form_new_twicle.is_valid():
            twicle = form_new_twicle.save(commit=False)  # Don't save yet, pending actions

            twicle.author = request.user

            twicle.save()   # Done!

    # Always create a new form so it's ready to be used (Enven after processing a POST)
    form_new_twicle = NewTwicleForm()

    # TODO: Tomar la cantidad a mostrar de las settings del request.user
    last_twicles = Twiclo.objects.filter(author=user_shown).order_by('-created')[:3]

    return render(request,
                  'twicler/view.html',
                  {
                      'last_twicles': last_twicles,
                      'form_new_twicle': form_new_twicle,
                      'user_shown': user_shown,
                      'allow_editing': request.user == user_shown,
                  })


@login_required()
def follow(request, username):
    raise NotImplementedError

twicler/templates/twicler/view.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}

    {% if allow_editing %}
    {#  New twicle form  #}
    <div class="row">
        <div class="col-md-12">

            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form_new_twicle.as_table }}
                <button type="submit" name="form_info" class="btn btn-default"/>
                    <span class="glyphicon glyphicon-ok"></span>
                </button>
            </form>
        </div>
    </div>
    {% else %}
        <div class="row">
            <div class="col-md-12">
                <a href="{% url 'twicler:follow' user_shown %}">Seguir</a>
            </div>
        </div>
    {% endif %}

    {#  Twicles  #}

    <div class="row">

        {#  Twicle list container  #}
        <div class="col-md-12">
            {% for twicle in last_twicles %}
                <div class="row">

                        {% if twicle.image %}
                            <div class="col-md-8">
                                {{ twicle.text }} | {{ twicle.created | naturaltime }}
                            </div>
                            <div class="col-md-4">
                                <a href="{{ twicle.image.url }}" class="thumbnail">
                                    <img src="{{ twicle.image.url }}" class="img-thumbnail" />
                                </a>
                            </div>
                        {% else %}
                            <div class="col-md-12">
                                {{ twicle.text }} | {{ twicle.created | naturaltime }} {# TODO: reemplazarlo a pata porque se ve raro! #}
                            </div>
                        {% endif %}

                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}